services:
  db:
    image: mysql:8.4.5
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always
    volumes: 
      - ./database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wordpress
    restart: always
    depends_on:
      - db
    ports: 
      - "8081:80"
  
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes: 
      - ./:/var/www/html
      # Aumentando o suporte de imagem e tempo de espera
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      #- ./wp-content:/var/www/html/wp-content
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress